apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: m2q9pk222-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-e621fe3676.rg4c.p3.openshiftapps.com/rhtap/rhtap-qe-go:b4cab9a22e2153abf905c06c282fcc75ac914a6e@sha256:21fe322a38e183d1163d451e0402f445f6c411d08b7483668866854da38d2e70
          name: container-image
